text = open("src/parsing/metadata.py", encoding="utf-8").read()
idx1 = text.find("class DocumentMetadata")
idx2 = text.find("def _embedding_prefix")
print("=== DocumentMetadata + ChunkRecord ===")
print(text[idx1:idx2])
print()
idx3 = text.find("def parse_and_save")
print("=== parse_and_save ===")
print(text[idx3:idx3+1800])
