text = open("web/static/app.js", encoding="utf-8").read()
print("currentBlockEl:", "let currentBlockEl = null;" in text)
print("data-cite:", 'data-cite="$1"' in text)
print("resetSourcePanel:", "function resetSourcePanel" in text)
print("showSourcePanelSkeleton:", "function showSourcePanelSkeleton" in text)
print("renderSourcePanel(sources, blockEl, isLow):", "function renderSourcePanel(sources, blockEl, isLow)" in text)
print("highlightSourceCard:", "function highlightSourceCard" in text)
print("mouseover listener:", 'addEventListener("mouseover"' in text)
print("showSourcePanelSkeleton cagrisi:", text.count("showSourcePanelSkeleton()"))
print("renderSourcePanel cagrisi (block,isLow):", "renderSourcePanel(data.sources, block, isLow)" in text)
